environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - PYTHON: "C:\\Python36-x64"
      # PYTHON_VERSION: "2.7.x" # currently 2.7.9
      # PYTHON_ARCH: "64"
      # LXML_URL: "appveyor\\lxml-3.4.4.win-amd64-py2.7.exe"
      # PYWIN32_URL: "https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win-amd64-py2.7.exe"
      # LIBSBML_URL: "http://downloads.sourceforge.net/project/sbml/libsbml/5.12.0/stable/Windows/64-bit/python/libSBML-5.12.0-win-py2.7-amd64.exe"
      # NUMPY_URL: "https://www.dropbox.com/s/sq1d10lo9z4k7mi/numpy-1.9.3%2Bmkl-cp27-none-win_amd64.whl"

install:
  # - choco install -r -y make
  # - choco sources add -n "msft" -s "https://go.microsoft.com/fwlink/?LinkID=230477"
  # - choco install -y libxml2
  # - choco install -y libxslt
  # - choco install -y strawberryperl --allow-empty-checksums
  # - "SET PATH=C:\\strawberry\\perl\\bin;C:\\strawberry\\perl\\site\\bin;C:\\strawberry\\c\\bin;%PATH%"
  # - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # - "%PYTHON%\\python.exe -m pip install --disable-pip-version-check --user --upgrade pip"
  # - "%PYTHON%\\python.exe -m pip install --user wheel"
#  - "%PYTHON%\\python.exe -m pip install --user numpy"
  # - "%PYTHON%\\Scripts\\easy_install.exe %LXML_URL%"
  # - "%PYTHON%\\python.exe -m pip install --user networkx==1.9.1"
  # - ps: (new-object net.webclient).DownloadFile($env:LIBSBML_URL, 'c:\\libsbml.exe')
  # - "%PYTHON%\\Scripts\\easy_install.exe c:\\libsbml.exe"
  # - ps: (new-object net.webclient).DownloadFile($env:PYWIN32_URL, 'c:\\pywin32.exe')
  # - "%PYTHON%\\Scripts\\easy_install.exe c:\\pywin32.exe"
  # - "%PYTHON%\\python.exe -m pip install --user winpexpect"
  # - "%PYTHON%\\python.exe -m pip install --user pyyaml"
  # - "%PYTHON%\\python.exe -m pip install --user pylru"
  # - "powershell ./appveyor/install_numpy.ps1"
  # - "%PYTHON%\\python.exe -m pip install --no-index --find-links=c:\\tmp numpy"
  # - "%PYTHON%\\python.exe -m pip install --user numpy"
  # - ps: (new-object net.webclient).DownloadFile($env:NUMPY_URL, 'c:\\numpy-1.9.3+mkl-cp27-none-win_amd64.whl')
  # - "%PYTHON%\\python.exe -m pip install --user  c:\\numpy-1.9.3+mkl-cp27-none-win_amd64.whl"
  - "powershell ./build_sbmlTranslator_win.ps1"


# branches:
#   # whitelist
#   only:
#     - master
#     - release
#     - development
# platform: x64
# cache:
#   - C:\tmp -> \appveyor\install_numpy.ps1


# build_script:
#   - make
#   - make install
#   - make test

# artifacts:
#   - path: '.\dist\sbmlTranslator-Win64.exe'
#     name: sbmlTranslator
#  - path: '.\dist\sbmlTranslator-Win32.exe'
#    name: sbmlTranslatorWin32


# notifications:
#   - provider: Slack
#     incoming_webhook:
#       secure: Ee9fFcoV1ABKmTKowaok5sUiOlRSGzCpWtwNIBFC0PpauqK+/mEt9KjeUXWsb7J7uFcAb1CKo7y/FFhHEJH6pWGMn5oV283uVnqZAB8Chac=
#     template:
#        "<{{buildUrl}}|{{projectName}} build {{status}}> on {{commitDate}}:_{{commitMessage}}_\n
#         Build: {{buildVersion}} (<{{commitUrl}}|{{commitId}}>)   Author: {{commitAuthor}}\n
#         Download Executable Here:\n
#         <https://rawgit.com/RuleWorld/atomizer/master/.Atomizer_Beta.html|https://rawgit.com/RuleWorld/atomizer/master/.Atomizer_Beta.html>\n
#         Build Details:\n
#         <{{buildUrl}}|{{buildUrl}}>"


# deploy:
#   provider: FTP
#   protocol: ftp
#   host: ftp.midcapsignals.com/BioNetGen_Beta/d_appveyor/
#   username: roberthclark
#   password:
#     secure: K22E4pSAup6/htlGmoSBMw==

#  To encrypt the password for FTP, do the following:
#  1) Log on to Appveyor
#  2) In the upper right hand corner of any page, click on the down arrow next to your username to get a list of options.
#  3) Select "Encrypt data"
#  4) Enter the password under "Value to encrypt" and click "Encrypt".
#  5) You should now see a string similar to the one next to "secure" above.
#  6) This password can now be copied and pasted to replace the encrypted password above.
