environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - PYTHON: "C:\\Python36-x64"

branches:
  only:
     - python3

build_script:
  - "cd .\\SBMLparser"
  - "%PYTHON%\\python.exe -m pip install --user -r ./requirements_win.txt"
  - "%PYTHON%\\python.exe -m pip install --target=. python-libsbml"
  - "%PYTHON%\\python.exe -m PyInstaller ./sbmlTranslator.spec"
  - "cd .\\dist"
  - "7z a .\\sbmlTranslator.zip .\\sbmlTranslator"
  - "cd .."

artifacts:
  - path: ./SBMLparser/dist/sbmlTranslator.zip
    name: sbmlTranslator

deploy:
- provider: BinTray
  username: jczech
  subject: jczech
  api_key:
    # api key from https://bintray.com/profile/edit
    # encrypted in https://ci.appveyor.com/tools/encrypt
    secure: XzrXGPWsRRrx8DZTJSNJpLkMZrxlXF2vdeao4CCBiXUtKBuxR7Nj2CQIBy3L3bSB
  repo: atomizer
  package: atomizer
  version: 1.0
  artifact: sbmlTranslator
  publish: true
  override: true

#  To encrypt a password, do the following:
#  1) Log on to Appveyor
#  2) In the upper right hand corner of any page, click on the down arrow next
#     to your username to get a list of options.
#  3) Select "Encrypt data"
#  4) Enter the password under "Value to encrypt" and click "Encrypt".
#  5) You should now see a string similar to the one next to "secure" above.
#  6) This password can now be copied and pasted to replace the encrypted
#     password above.
