os:
  - linux
language: python
sudo: false
addons:
  apt:
    packages:
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
python:
    - "2.7"
cache:
    - pip
# command to install dependencies
before_install: 
 - pip install networkx==1.9.1
 - pip install pexpect==3.3
 - pip install lxml
 - pip install pyyaml
 - pip install python-libsbml
 - pip install nose
# command to run tests
notifications:
  slack: faederlab:8ABlK9WdYWbm2sc4UAkaRTGB
script: make; make test;