os:
  - linux  
  - osx


language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
    - perl
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
cache: pip


before_install:
- source osx_install.sh
- sudo -H pip install -U pip wheel



env:
  global:
#       FTP_USER_1  
    - secure: "Kfcg8+03xvhk/kZnbneg4z63ABt3XZyap3TXfhdsacbeq2TbQ+Vd6UqzKVWZ7Kr0df1QaXPhMl1/IvvPB9EJIIiQxvX52XJVWsAs4kbOjfplLBUU2i/9G4vwJNpIqpNq4/VF2jV4YsiJmouBnU1zrTLcp8NP9/ZAkoi12mykQh8IjMZ9CIv5xOhJKuvV3DaSQK5ulafGROLM60POmbMJf2yW2RlhWRL3tBk/4KZj7AWJeV74YKAfaLk+mC2ppANOlorzxI9TUrXhg7JRKPsumQgQsg6RWH5+DAUTl7B+9RElLw0dItA00J9QQrkFzFAyqePB+XkB83AcGmW8VWIo4PAJ6vqmtt7bLm8NKmaOh8/VF9YfmVgoOmhe+kdKxEAI5ItHYUES10o65k+dueYWM+vYyBpR3RFG0AbZgstPZkoV+151WvuI9l9m8mlZPJqw8Avsc15pLqf8AiPS5aJ1s98Rx47keue5LVZDLOXxoJPTZOsB7Ci+xApD7YLsTUZyB5WKHj0M838BCOzGBYNsLVkaprjtztpI3bIAdLuBWiRtyJIusSPeInlG/X/O+8YJ6CLfnpkuQ+UYckqL7h9+04FEVuYMxeBfVs/4/P0311fo3BBVGZLW6wqgXXmNRq5nwrxa5Rj+oemy6EnOqP90SgvQvQ+ByhLvo1gzlaX1JFE="
#       FTP_PASSWORD    
    - secure: "DxRClOWGBhxJUkWEGhZMNZzPMRYxf6FA6m/9HsQhnLrPO9QteF4xAt7FePPoPxUTP9/+oX+eirwBjwbfZHYqxu140m8FQyUasMhUWDrzJFQf9d198JmBkuzc28F3J/zqNUaufIsQSTMETLpBLvhts36MZw8tqKDtCnG8nGJf6ibL3VolkMVKg6eWXpA0RYoS4JzHr/RdX34AJIDLxHiq0NWFWNqgXZ2Y/z8hKTmjwWelw+KDorr00UG6X01MRFtjV1AivB+YfIGlzCJa2jzdOTjC9w0hh0HGqmHMhBszeUAM2mtixY/fAKZ5VFt7f1D69X4PRORxYjnrKHFV12jAyEM1eTKtaTYlXDfWmj2aQSmQixpmwAt3K7fcpvhVY690C+yrUT7dm2UdsscfNGP6z0SEyzY9p/jvp/37XtbxGQChTEckV++MtXHPUUKJ/0zQqy5B12e613hiaaYZRUu7bJteYX+aapyVypjcmxqkzbG/yIokRLzq6LxyKK9eyFVhuvs9ANrO1jqijehY3fciauulp/MNt7OXcBpaLCmji181UsRf1fH/DRoEK7dLPGT0jAsj/RsQZKxonBwmJE5BPjm4ac3qEApiGcop1Ah+UFY384zzsyN5Ymr9UtD3fOdmYSdgrPa9FcM7T/OwimS8pQLaiaVOd7D1BW37l2inMLc="

#before_deploy:
#- cd dist; python changeFilename.py; cd ..


script: make; make install; make test; cp ./dist/sbmlTranslator ./dist/sbmlTranslator-$TRAVIS_OS_NAME ; pwd

#deploy:
# skip_cleanup: true 
 
notifications:
  slack: 
    rooms:    
      - faederlab:tEor7269wGs9ylzYYu7hVGq9#build-results
    template:
      - "Atomizer build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"      
      - "To package Atomizer, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


after_success:
  - perl .make_tar.pl  --platform $TRAVIS_OS_NAME
  - "curl -T ./dist/sbmlTranslator-$TRAVIS_OS_NAME         -u $FTP_USER_1:$FTP_PASSWORD ftp://ftp.drivehq.com/d_data/d_travis/ -v"  

 
#    The FTP_USER and FTP_PASSWORD strings are actually defined in the env: global: -secure: strings above.  Those strings
#  Were generated using a program that may be installed on Linux.  Documentation can be found at: https://docs.travis-ci.com/user/encryption-keys/
#  To make a long story short, the program may be installed on Linux with:      gem install travis
#  the command to generate the FTP_PASSWORD string is
#
#              travis encrypt  FTP_USER="password" --skip-version-check -r RuleWorld/nfsim
#
#  The password should be surroundedd by double quotes, and the -r parameter indicates the repository for which the password
#  will be used.
# 
 
 
