os:
  - linux
language: python
sudo: false
addons:
  apt:
    packages:
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
python:
  - "2.7"
# command to install dependencies
before_install: 
 - pip install networkx==1.9.1
 - pip install pexpect==3.3
 - pip install lxml
 - pip install python-libsbml
# command to run tests
notifications:
  slack: faederlab:8ABlK9WdYWbm2sc4UAkaRTGB
script: make; make test;