os:
- linux
- osx
language: c++
python:
- '2.7'
addons:
  apt:
    packages:
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev

cache: pip

before_install:
    - source osx_install.sh
    - sudo -H pip install -U pip wheel
    - pip install --user -r requirements.txt
before_deploy:
    - cd dist; python changeFilename.py; cd ..
deploy:
  provider: s3
  access_key_id:
    secure: CvmkNHPkA/GIafzLnzAUBpBCyH86/D27SUmkojPxZzehfsHYHxOFIYmYvjMdTBNPzfS5Qisot3VlM4VBImJ1NkmLQThPnuWE3dAB1RsCV46ivbjNfmF8oRW/ssjuoBQtTBmZwAkvzSpW1UtVIkSWfxOrADwn8IsPGlWfFrbcbPNJbSYIcjL8vCtQKwJyPk8fcLN9GrEFVJnB5lcvaHkcduU4vnn1cLdBJbcA4dMX1y9UzZeR++DWvYEdI61FXy2k3E1WOy2n9KGLABTAnsMatfL2lPPO+npK7R2fN38d2uOG+EoYmP+jqxyxoi9B8frbjzxrqm4XfFQG1nx66m0qHiWM477wug6MKS7aM9uAJ36W3utNOi6eM+prUeG1GfbUEBdx+TJJCiriTDF2kb6YyXJsvryddmBUzeX9AJ2gp2Hjy3wZwV6ok05ypJjTtq1LSP/TPHBCeVoL4UKNYI9clyeQx4tjNqB7pdIzeG48guoFhpnNDFaFx+7qtH6Xj7urTPXR9GWzY3ZXL+PgMFbUWoTeQQ4R101B3byP0Xfgp8EFrJctNVIetA0rK/oYY96+2LKg9iWiQN5BzWT/B9WIT+wgMC5LKVmtIs4IqbSFFRU8tTHygU8W+JeERA6TblSNter3M7pN1H9+/+OAgmQG1jsGPawLoXO0jyh1lmh61fY=
  secret_access_key:
    secure: rVRYIB86hhRqnCzaUpNcfLU7PvzBMztL9x+8aOK91/o8yqrqHTYZb6E2kMHGlcOY3/iwBXjicVhh1HNm6t35YfhQi9xiwhx5DkUfTRsuM1s14fArmqddnHgkXDwQhfVK5xLFCEpH+lYUAs45BkgNjC7+t3EwMfXdLorrVLI6jM/kncheZOe7qzBoIdpCpm2lm3pQMyKqBF1eo36e3k4Q8fuj+U3o8/ri3PMnWC27Jk0mgm0dE5zLmY9hOGDqDjISQLHfRQElnBuSgHacDcljmQjSwS85mqRZdzSsmKuVZCmZ8M07g0RrjVM0xhrvdHBw1Lt+0ArGlzf9YVa89cRUS118/uYDtKqNKw3TkX1ozyd0GcMcuGxY1xAeiCvxCfI/S9nbtkBWt4V3vqqFR5fmabMPypRvjJUwrpXyIwP2ZbREwjM+o64PxQoHnsf3Tw1MURNSecMUv+B9oyopcAxovtK/3uSNTCtSololLpPG0s32pJOmADNoZgHf3/JbDG6+BSI5Fxvg+ZwgH1VFGULcbtsR17hnoGKUJfor1eImXiVn7PH05QAGn0KifILfKNCWUS4k2wgxMFvfpecVLTcilgsbu5EwAqOtIOKYNMBzl1pVTBi1GIgrnExC4ixX5sNf+9ZhImy9eyk9ZYcbyxczd2mC4gkLmreJus4szcSj1p8=
  bucket: ratomizer
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  on:
    branch: development
notifications:
  slack:
    secure: uUR4a4uFJTuCaGmSR8mOMrHRmzy2T35wN7MhLS4p/AbQekdMxaEAYBdVtqyb0IlVO58GJ+xPJjCh0f2IhECbYDb8Lyz7tAE41NnYcRrf6qCyv9g8BsvYxNjTbExr4A6bnSu5AKHZjbv9blGPE0dHR0Arskgrj4nTRYNhiv9cLCZ0yGZhKQkV9YMMfT6gNjDMHot6fLrbDCMcBZ7XtE1IGhOETWBGFQt1jj8eiOs3ZMWkVwUuLIF/fRpVjwYFkgUnQVAfQ0bke0/1R9cWeh/bIbKqDhYP9SGW4QD8B3GMRZ9kqRNfjy/DmD/Ss5myCVvdnLVlNp8osT0+UCHhfop3EvYwwE8wgcoapsPXMmHohVKiCwRw0FuPX75nm+btX2EQU1aEhpX2vTV/yEl596YhlFAOoKLXNLJQGkAjWmYalmBh8L0ZokRPDI28L/RGqepRYnx6lPdzEZpcCQMQhlB4TA1pAH/CgJaNMruvqsBAIpWa64+T1icT92BpXgoDPPOCkJLwKTfS2pgJfqvJhUeTYtOQbOlJczrPmrsW6zWTMUf0M6lLjlbl2bbR4e4MFG04/HpGFXj/sIFuwwSJhcuwdMJeAzXdFe2e3N2Oj0Y9NfEWLNM1KM97rqme4q1G8JN/uy+ChImNXD0312nkHlbAZc4SWrbfgD5qp3zn73kbARI=
script: make; make install; make test;
