os:
  - linux  
  - osx


language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
    - perl
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
cache: pip


before_install:
- source osx_install.sh
- sudo -H pip install -U pip wheel



env:
  global:
    - secure: "jq9RObKHDfQzACQCHWoZ/aJrjHw0T2n3vC565NN7FiPEsuPrR8cYLzXqNTl3KtTzD1IQrzpGYwW3qYaEVa8yqRWsGMvuIWptC+mcz2FtSLaePe7Rq9nikPByTbqT539kJn17wU1Q6NJEqbfykbBiopdbBvx1CnJLjCiZiGTZaNADbiRiQbOQ3dq6m1bJVM/dDTIuuxL0yDVAMWkdluEt3eT2pE1twGXVO22rwrMLSTRIkw/KjriBk/FCE2oEJ9RqwAWRRuzAwfWcG4/GziKP5PMFdAGHkECMBpmdpBjWMPcRsOmXpWCJgVqT7No6kcUB2+2tjJOrGGHEIzh0NyHn3IibcLeFCXSHiD1rLS/fz6wi9nwkqsA20QEgeEUTpEG0CkVk0GpvsuWhnDJ98ntckGGYMsDamLF5nyBPyVAN0Q8dAvuZHgv+XAupIUXfn6MlR37vwOy4Vf8cqGclCwh7koym6cp/mERELaxpmqEZbkr6hdp3+7MXZ2sw4lVaFn7Um6eYlgZs1TLfYsn8NGQF+TUVcprHLjM+/CtFIfJOkuZSL7KDje9pXHJdwhG7dyK65kY+u2O9XkJkwol61OiVeRfEIa3Z4TYuB8jKn/pdvEhuDFvjJaimBc9OTbE5gKQdyGyf2JyH5Rw7JVS/VNIReUI3+64df9ekMYsULcIgIHo="
    - secure: "vta5PH1ZqG5m57Se3WzxjCWHJwubnfSUUjT6UejYBd4OwaoIXzR4DKE74BSZEs+UY4D1Lxue1Mksbtw5AWvj8FJ6pgkSMOLbyXl6L4c0z74FlavMMASPKDVgEhpDfvZpAfBi5qJewte76rICZpAa894g2prc/L6T0vf/XTY4esRu6BYLjfHGZG2ERyOcERZkVJJDGQTo3DBxAAWtinQyf/IPqvwmbfw1XcRfXHHb5+XeooAZMfPcaroqBRQjrnuiUwI7XMW4c8p/4/1pups6S+p6qP9bHTj/kg0HiSdfDZwrawo8XpDPjpssPHQseOqSbr7Tbej5nxVzUmkfsTbZrw/aSnmuI53t+U9wF1i6KwqHc/ChO1md4qBHV6WgvVYbXFjRDibAVwchfyOS0G3KMYY1SWhlm7YQ4sNf9vIHQVEoeG0WpqIc7j3ok8XNfol3CSLbQWWp4NPgv5Jh3GQGjnARti952HjaOhaKmesNphogkWQagi7ketzbR+Jj7gKLHKLNoTyMlK+BzCqNnX1A9tTe7xY3+Q3u/A/418ejr7Xm00O6Lckpi1t2SsFSwTbfIYDHnGtW5Ro/mzQPWKHgctdBTFXRT711+tv9HFY9w7Pb81489xZP8eu+wwpTgodSQjM7F5iSyWjV5nQ79+iJCNh+tifgRyhjcQ+SAPLzz5w="

#before_deploy:
#- cd dist; python changeFilename.py; cd ..


script: make; make install; make test; cp ./dist/sbmlTranslator ./dist/sbmlTranslator-$TRAVIS_OS_NAME ; pwd

#deploy:
# skip_cleanup: true 
 
notifications:
  slack: 
    rooms:    
      - faederlab:tEor7269wGs9ylzYYu7hVGq9#build-results
    template:
      - "Atomizer build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"      
      - "To package Atomizer, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


after_success:
  - perl .make_tar.pl  --platform $TRAVIS_OS_NAME
  - "curl -T ./dist/sbmlTranslator-$TRAVIS_OS_NAME         -u $FTP_USER:$FTP_PASSWORD ftp://ftp.drivehq.com/d_data/d_travis/ -v"  
  - "curl -T ./dist/Atomizer-source-$TRAVIS_OS_NAME.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://ftp.drivehq.com/d_data/d_travis/ -v"  

 
#    The FTP_USER and FTP_PASSWORD strings are actually defined in the env: global: -secure: strings above.  Those strings
#  Were generated using a program that may be installed on Linux.  Documentation can be found at: https://docs.travis-ci.com/user/encryption-keys/
#  To make a long story short, the program may be installed on Linux with:      gem install travis
#  the command to generate the FTP_PASSWORD string is
#
#              travis encrypt  FTP_USER="password" --skip-version-check -r RuleWorld/nfsim
#
#  The password should be surroundedd by double quotes, and the -r parameter indicates the repository for which the password
#  will be used.
# 
 
 
