os:
- linux
- osx

dist: trusty
sudo: required
language: c++

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3.4-venv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi

script: 
- make
- "mv ./SBMLparser/dist/sbmlTranslator ./SBMLparser/dist/sbmlTranslator_${TRAVIS_OS_NAME}"

deploy:
  provider: bintray
  file: "./bintray.json"
  user: jczech
  key:
    secure: mim54ge1ziCzoD+CpBy6F+Se2aR6KF0TNA/ML6wj5rWk6/qzG7LLrdN6udOAD/LFV3l52awn0GmsEMQzdMmHKtxCqkdgt+FCrN85y/sZBx0w+ul26uByJoc0W5O6s61FyVStEauMxHC0t4PFYf0KmRnO0Sj1e237ceyTvuzqGIGLlQlu1s+zlMnpW1JNhT2QceWwiuML7PYQU1t76QXiNkE72DKX9k7umaaeB3mFRI3h+pWPOozzIjS/3iFaI5olLgnSF6rm02Xj46TTXiq6WqkvqK00XU+WIs6BLm5Qyz49gFVnTB9C8vldOoUwLiKAJiVO3JfdwWKVr3c/iN7Bnt8clhgPHGLtsTrpfQRsw0oz9Q5aNY/ZV5DKSi+4TRse/633MHHTaP93Eb7sdzJJ0cDN8Hx7/hUEiodYc1JIFALD3tLBfO9wI9yDUhgtMcHsSd8MlK+StwXTy/xtxfiQpYxlhBpw47VxhE0JHkjRZdKmuneruoq7fKqBcwi/yERWKr7VNEKmFJ1pNBqCXEk4T+FZCnUv2sUWQMbW/vdBDlVPp2SfO0EEE6spbM3n5GNzZfupJoqTUrATNSrecoTDrp4qC5sTiOUt2Bu0+ViPW9qKCsNSMTg1VfZgSRTg84H8tH20iE6FdEurKTcYvh0XniVPvH19HIlSAtClie4n4a0=
  skip_cleanup: true
  on:
    all_branches: true
