os:
  - linux  
  - osx


language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
    - perl
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
cache: pip


before_install:
- source osx_install.sh
- sudo -H pip install -U pip wheel



env:
  global:
    - secure: "M5hBkNygj5p2Uazb1OuOxw/Z36Iaz1FwPN0JL4PCaocyMlR082anZepjUHEGZy6wuMNu0PN4+x4SzIVnSGBn8Vu4kL+CGxpeyvpdIpP2ZqJcsZLv1GQYSh0ykjBPBIoLkETu8CKkJuhQx1r8MDHAAg6aBxaAKaAuPj0Bd7BqcnIad/R2tETPGMUCEmE0f344EBCL0DH5XmrPSusa0BPYwQlScdJjStYrbj4KRAuRbqja7XZ4hoMXzKhRSKjdVe+4d024VTNnJ5HO/kOQ3fvR7+Q/UubFd19uFDDVZ8yOzCTWAahx0pzyHZN+HK5/4muewDMoebmgLA/0QVJ9IagQ8k26uZ3Q276+3Yx/UQHLOEIidcqwK99Bs7Z/J7wPvRs+UWfEfzKIOIWPDXoKyZpuxRBe/6DLnyjELEm8/kQ+zJ59mWM5c6PKVtqweCdeUiBttaodPid9k3dKtktilnP6IZiGT4oM1qaJJc1EY8FfT/g67xR1g0Zyn1aeapLQ5dPCs/9u4GYaPlcN4CF9JnE+6uirRB1IevSMh6Ken0bR3h0w3KZaNUp1/l7FtJuwtnwGtApk96BuNV3biwZgp53+1yG/b6WS1MfLI80tyO8uldVE0TfdHU4GtnpsqggaFZYypgF/6gq/YXI0L6gqgd6kjcU97PKtBuLlYo79mSU0DqI="
    - secure: "mBI2ds0URvBDhBl+eDJVEOMmT9RJrjhHc7nHft/8c9iwvpcSJj6yg/rYlqqXJPMGO5SeRgxAluhSwMkDV+n7JijIl9+UxoULeg85YK0n5SgVk8lx/xqCE3kGFxpy21n++PRlURhxcBcCMS1pYg9XodIrMEWhNsYyoN2fDdNfkjqptw2bYC2HEzDA5WaNYwQAyD2u36TVFettiVjBJ0DBXBO+yd77AuV9fXfduWc9NLeHQTN3JWdOXo4iaY9z+1tj5zGmhkg92GIEEWAG2xGLuJNNBIV0ZNx0OovHf32M+mIWoMuJtAEjPJfSkzJAUv6gdaipdN7LS2pSVHDs6Oji9lqktDWs6zPT9mpi6r4+ukq88C1hCeYlXI4hwVi2MSSd5z8zR6p55UYNA2NflwgWRSuKRbyQ2gI0uCDLV7bKmcSe4BcWIh8M9yK+BWnffPaL9ODrkKx9l6xdl4GqsMnUdLy8oDKMiyRLKkW96LTMZSiNOpJIw2y4tum7Q/ke2CUmruCbbwGlT9fqonXvVN9JUonnzmjd+YwOu+vQDiYI45Y955ebcwdpo7Le490niJpwgI8O1KG/pjR5Qt+fzWpWChKZx2cIRtE8uVLl3maWHByFMxZ1hehIZjgONvxOMKwHEGr284LVUeOLai6v/ckivbA76dmsKwrgiH9SiqIGv4s="

#before_deploy:
#- cd dist; python changeFilename.py; cd ..


script: make; make install; make test; cp ./dist/sbmlTranslator ./dist/sbmlTranslator-$TRAVIS_OS_NAME ;  pwd ; ls ./dist

#deploy:
#   skip_cleanup: true


after_success:
  - perl .make_tar.pl  --platform $TRAVIS_OS_NAME
  - perl .make_html.pl --platform $TRAVIS_OS_NAME
  - "curl -T ./dist/Atomizer-$TRAVIS_OS_NAME.html          -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/d_travis/"  
  - "curl -T ./dist/sbmlTranslator-$TRAVIS_OS_NAME         -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/d_travis/"  
  - "curl -T ./dist/Atomizer-source-$TRAVIS_OS_NAME.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/d_travis/"  

 
notifications:
  slack: 
    rooms:    
      - faederlab:tEor7269wGs9ylzYYu7hVGq9#build-results
    template:
      - "Atomizer build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"      
      - "To package Atomizer, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "
#deploy:
#  provider: gcs
#  access_key_id: GOOGHK4SCMDVVDNXWLUF 	
#  secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
#  bucket: travis-rhclark-sbmltranslator
#  skip_cleanup: true
#  acl: public_read
#  local_dir: dist
#  on:
#all_branches: true
