os:
  - linux  
  - osx

#  This causes Ubuntu 12 to be loaded.  Remove it to get the latest version of Ubuntu
dist: precise

language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
    - perl
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
cache: pip


before_install:
  - source osx_install.sh
  - sudo -H pip install -U pip wheel


env:
  global:
#       FTP_USER
    - secure: "Q1tLAiZzPIfT64OqRI62qSK9n19kEgbG3+dJ64GleH+g5aVFCAi/JSeJqs5vg88wqLzb7EERhIl76hAlTXhK4cHimhldF4G+KeQCW1CSIJtQ2oE/EdmsO8XLNtTtgHzLx2oWG+lUfB2Ze1YVi6Awnsk0D54iYzdOTSSBQs6v1iRDdZiDWTunhikIhk4HJXfw/p/yRVk0WbfLKEeAOvuTUCUJFtzsXd3fWpJnUzW3CgkHkA0YO/mYr94WGoYVvXIWi/82eLAFMnM43fPsZtJQ/oRkuL6ic9Gbn4ctX0QRKNyi5YBUOpATLOSx/zFBXSpAvtqGJRgtc01p6f+Vk/6f8k41tJ53vW17M+IKzoaxIM2UMnuGbr8jPw7q9sM5kKa/aIlvDuQcWD6tZv3FH/f2vBN15jlKqXYauc3zKvJ3N6hiJv1RDBGB3h8N9bD/Wm0fGkJTGC6etq7byZo87TeuBHV7QeuU51QxjFho75R5loqiArlhubehGGDBwhEyz12MrWEQOFnA/8MOKfVnPFA2z2MhkYz/TgXI2HX3TnB0qJvdxdkAsJY9nIwqjfZJ2USWsodJZx14a09+SIb/WHetcI892pPlfyJJL3l5IgxJg99Z2e1+VSbPr+NMQ32VD75uYuVWjHya85asqA5vIqVQUWcJdNM+Z4/JjUXnUQUbAMQ="
#       FTP_PASSWORD    
    - secure: "nh5DvWxu1SdchfRBFgVchZxJ/UhUpl+YLB5xY/yJHnlpdajev4e5Cnx6ZswIUGcJq8vkjmLyD2HOiqpXBLaLE400mqxbvhy5vQ4ytbbfwg8ZYa50lMqbPeV2PycM58pxgSnpNYYm+lm4E+ql967VgTeIrWO2eDGXNcGMzx8Pkx+qyw9bOx4Qv7P2OTzq2xx4V708/0tATSlsmdyUkZB+gQ3K3cCOWm4Dlv+fDPLLTftFrwOMKxHU4gaM0QwQ8pR8Euo2mQhTPNXf1n+olnGL26MSmmkbQ9GQhmqFsXZ2Tc0qeB+Eef4ANjRQ4r1GEt+7u/NHZNG28Qi2Oqs9rZZX+pvwsK+1JCjbOsI2tIXzJCaVnyaHgp7+kKkMHqQul2N8ILGrNWb7bRSDlVq8XfWmux7NnwXh+JR0y4LrsAYaaiehyYrj9Z/u0l2SP4wRmFQu5HrzCIsAa9JgQzWA8YPHjAYdmEs0j6rtIEWsl13itF9cFZG4B0GtwsIrQXqA6Qb59if9cS23UFehonUplPLURtIT3Y0c12tF9vWdE2sEMyMgUgKriHde4tbiyXpX+GSezUKaHe52XTiVic3fQ7+VF6GagTsL9Nfy3Eu7BYQRs3iWbDXTQbQWXexNoMNqjVOYMuvPAoXD3CCz9urNKrPW9WzHerMuffXBeDRm0ZV2Szc="


#before_deploy:
#- cd dist; python changeFilename.py; cd ..


script: make; make install; make test; cp ./dist/sbmlTranslator ./dist/sbmlTranslator-$TRAVIS_OS_NAME ; source .curl_ftp.sh

#deploy:
# skip_cleanup: true 
 
notifications:
  slack: 
    rooms:    
      - faederlab:tEor7269wGs9ylzYYu7hVGq9#build-results
    template:
      - "Atomizer build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"      
      - "To download the Atomizer executable, "
      - "Goto: https://rawgit.com/RuleWorld/atomizer/master/.Atomizer_Beta.html"
      - "To package Atomizer, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


#after_success:
#  - perl .make_tar.pl  --platform $TRAVIS_OS_NAME
#  - source .curl_ftp.sh  

 
#    The FTP_USER and FTP_PASSWORD strings are actually defined in the env: global: -secure: strings above.  Those strings
#  Were generated using a program that may be installed on Linux.  Documentation can be found at: https://docs.travis-ci.com/user/encryption-keys/
#  To make a long story short, the program may be installed on Linux with:      gem install travis
#  the command to generate the FTP_PASSWORD string is
#
#              travis encrypt  FTP_USER="password" --skip-version-check -r RuleWorld/nfsim
#
#  The password should be surroundedd by double quotes, and the -r parameter indicates the repository for which the password
#  will be used.
# 
 
 
