os:
  - linux  
  - osx

#  This causes Ubuntu 12 to be loaded.  Remove it to get the latest version of Ubuntu
dist: precise

language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
    - perl
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
cache: pip


before_install:
- source osx_install.sh
- sudo -H pip install -U pip wheel



env:
  global:
#       FTP_USER_0  
    - secure: "eSJMiO//84IY8AmiDQCubIExrCcYlJNvdl/ZPDZSM7FoZ6528PEgsfqepVK4nD7P7Wg+1Fqz6fkNzpeTeiNX/ve9XB2pmEplaDz3QWVFIujhcWvbwMWlssd/Ng/CMh4ittdkowGVcOKrSfgJk4ECgyzLYeteT9VkAB0HKJ54asiFPvvQez+11vuZ9dVFNYxQ7LLWMwvher1f7ip13l41yZ7YjVSvGKr+rb3+/M3NJ+hOaBfPjYFbp4wqyEzlIptRby+425WMn5VOkxCOvNPqma1d8bL6sS9NtQafuWrDotafnaqHfldtiT/T9TGdS4XaX7mf+KwUHpjaEyhmh5ipnhFNWCKnFGlt5yS1zKhSm+ciXAxoQ93m3c6KuVuXkSMyHioEV85LKeZQeRXEC5KwcS32XMLgIlJSrtipXiSdYHf+Cb+wTzs5741rC4xR/S9jhBlpW4l1g3rLN9Xtpe/JI1ZynRU2bTQf4l7nfSCXe+lDywgGG8uALvr6G0c+KTVLPejuL5kbRw8IJ8RoeHvJTOkNcLOv4rdNgx1p91xkL4jKl+M4LH5IFibLBOBhIfmenZYnE3qjI/tK0QxGlc7k8wRv2ySyCdrArqFtQGFvBLH/ZRy7LPSc0L5Zime+QlR8nLUhR9cXiXa76ZJFRguIycmKnpfVVxTn8w+5sbw0u+U="
#       FTP_USER_1  
    - secure: "hXDhQvvtm32kH+cq/golT/WC1Gy/dWDLFELgln8p1UlfrvObVbkAoftUJBEcmGvo1DjEZSjHqUzEAmrqwTwX+4Mc68055EkuORK6iM2Kzx07Ve5mFCtGLv4im3Yh23sI/ni4KRPriWGWdJqP6LwEzpl2iPEIwsaOXLleY+/jznjN5Nv1+oEqeWUg5y9UHI4yzZlMFXBi/uMz//pqIfm9xzwByBbF8rNOdEQOxwFxO+0IcQq+8J+qRnKL3vDIXRMSdCKujdnRncm14U8y1TeAn8Ga3ncDS3GcJPB4iVSmPHhZ3vRYLQK32GrX+XHKcbjZMyw5+phzJCJCZkxGdY0rTc0on+49D+uwfpFfY/mjJZZmNKkUa/JIfLkMPSyurYjhxlaqkU0LeWfySOn/UqY8d/bT4Leaqw1rDC178GSpQpWJvpgdGhg9hukRXZHuiZ5JK2I/YE9cn8tCcMgrIgLyzOJVnM9t7of2jHSY0xOcL9kH0prmxwhE4YStcu04BzBy6y3IMpi1WrRSDXsh84oKdou7coUoJzpCAcjDfkDz2MvLxJNwluPo/tyXKz9wosD7RPDnIPh/m1K7QPlh/cq+RsiLU3Z0vG8P4km0ON1JgKf/6rWnaFJMIUrqwagMsVYeKFFR7sZJL9UztDlpBRSNbkx6i2w56Eh27GaWG9ZuHEU="  
#       FTP_PASSWORD    
    - secure: "DxRClOWGBhxJUkWEGhZMNZzPMRYxf6FA6m/9HsQhnLrPO9QteF4xAt7FePPoPxUTP9/+oX+eirwBjwbfZHYqxu140m8FQyUasMhUWDrzJFQf9d198JmBkuzc28F3J/zqNUaufIsQSTMETLpBLvhts36MZw8tqKDtCnG8nGJf6ibL3VolkMVKg6eWXpA0RYoS4JzHr/RdX34AJIDLxHiq0NWFWNqgXZ2Y/z8hKTmjwWelw+KDorr00UG6X01MRFtjV1AivB+YfIGlzCJa2jzdOTjC9w0hh0HGqmHMhBszeUAM2mtixY/fAKZ5VFt7f1D69X4PRORxYjnrKHFV12jAyEM1eTKtaTYlXDfWmj2aQSmQixpmwAt3K7fcpvhVY690C+yrUT7dm2UdsscfNGP6z0SEyzY9p/jvp/37XtbxGQChTEckV++MtXHPUUKJ/0zQqy5B12e613hiaaYZRUu7bJteYX+aapyVypjcmxqkzbG/yIokRLzq6LxyKK9eyFVhuvs9ANrO1jqijehY3fciauulp/MNt7OXcBpaLCmji181UsRf1fH/DRoEK7dLPGT0jAsj/RsQZKxonBwmJE5BPjm4ac3qEApiGcop1Ah+UFY384zzsyN5Ymr9UtD3fOdmYSdgrPa9FcM7T/OwimS8pQLaiaVOd7D1BW37l2inMLc="

#before_deploy:
#- cd dist; python changeFilename.py; cd ..


script: make; make install; make test; cp ./dist/sbmlTranslator ./dist/sbmlTranslator-$TRAVIS_OS_NAME ; pwd

#deploy:
# skip_cleanup: true 
 
notifications:
  slack: 
    rooms:    
      - faederlab:tEor7269wGs9ylzYYu7hVGq9#build-results
    template:
      - "Atomizer build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"      
      - "To package Atomizer, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


after_success:
  - perl .make_tar.pl  --platform $TRAVIS_OS_NAME
  - source .curl_ftp.sh  

 
#    The FTP_USER and FTP_PASSWORD strings are actually defined in the env: global: -secure: strings above.  Those strings
#  Were generated using a program that may be installed on Linux.  Documentation can be found at: https://docs.travis-ci.com/user/encryption-keys/
#  To make a long story short, the program may be installed on Linux with:      gem install travis
#  the command to generate the FTP_PASSWORD string is
#
#              travis encrypt  FTP_USER="password" --skip-version-check -r RuleWorld/nfsim
#
#  The password should be surroundedd by double quotes, and the -r parameter indicates the repository for which the password
#  will be used.
# 
 
 
