os:
  - linux
language: python
sudo: false
addons:
  apt:
    packages:
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - python-lxml
python:
  - "2.7"
# command to install dependencies
before_install: 
 - pip install --user networkx==1.9.1
 - pip install --user pexpect==3.3
 - pip install --user python-libsbml
# command to run tests
notifications:
  slack: faederlab:8ABlK9WdYWbm2sc4UAkaRTGB
script: nosetests
