environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"
      PYWIN32_URL: "https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win32-py2.7.exe"
      LXML_URL: "appveyor\\lxml-3.3.5.win32-py3.4.exe"

install:
  - choco install -r -y make
  - choco sources add -n "msft" -s "https://go.microsoft.com/fwlink/?LinkID=230477"
  - choco install libxml2
  - choco install libxslt
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%PYTHON%\\python.exe -m pip install --disable-pip-version-check --user --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --user wheel"
#  - "%PYTHON%\\python.exe -m pip install --user numpy"
  - "%PYTHON%\\python.exe -m pip install --user networkx==1.9.1"
  - ps: (new-object net.webclient).DownloadFile($env:PYWIN32_URL, 'c:\\pywin32.exe')
  - "%PYTHON%\\Scripts\\easy_install.exe c:\\pywin32.exe"
  - "%PYTHON%\\python.exe -m pip install --user winpexpect"
  - "%PYTHON%\\Scripts\\easy_install.exe %LXML%"
  - "%PYTHON%\\python.exe -m pip install --user pyyaml"
  - "%PYTHON%\\python.exe -m pip install --user python-libsbml"
  - "powershell ./appveyor/install_numpy.ps1"
  - "%PYTHON%\\python.exe -m pip install --no-index --find-links=c:\\tmp numpy"

branches:
  # whitelist
  only:
    - master
    - release
    - development
platform: x64
cache:
  - C:\tmp -> \appveyor\install_numpy.ps1

build_script:
  - make
  - make install

notifications:
  - provider: Slack
    auth_token:
      secure: jN4Fas2b8/Z1yNInrC6yWZf1sHzA5M7M/wANf+O4nRQLRqNqLsmNFGMNusaS+adFyS0kz3TfGBtLjAEKeh84jw==
    channel: build-results

